
DELETE https://backend-webservice-wslm.onrender.com/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3YWNkYjZkLTdhZDYtNGQ1ZS04MDk3LTIzZDlkNTA5ZDAwMyIsInVzZXJuYW1lIjoicnViZW4iLCJhY3RpdmUiOmZhbHNlLCJpYXQiOjE3MjQ1MTMxODAsImV4cCI6MTcyNDUxNjc4MH0.1IXMNSSbeVJ59K5ntnU-3ySA0uP38lYskA_HE_fpyg4




###

