import "../styles/home-globals.css"
import "../styles/port-style.css"

export const metadata = {
  title: "Portafolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang='en'>
          <body>
             {children}
          </body>
      </html>
  );
}
