import { Inter } from "next/font/google";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
import "../styles/home-globals.css"
import "../styles/inv-style.css"
import Footer from "@/components/Footer";
import Head from "next/head";

export const metadata = {
  title: "Portafolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <body>
              <Header/>
              {children}
              <Footer/>
          </body>
      </html>
  );
}
